title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Control
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# The Architect theme uses 'header_pages' to build the top menu
header_pages:
  - index.md
  - research-projects.md
  - publications-patents.md
  - education.md
