title: Rahul Mallik
description: Power Electronics Engineer | Grid-Tied Inverters & Control Systems
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
