title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Control
theme: minima
header_pages:
  - research-projects.md
  - publications-patents.md
  - education.md

