header_pages:
  - index.md
  - research-projects.md
  - publications-patents.md
  - education.md
  
title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Controllllll


