title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Control
remote_theme: pages-themes/cayman@v0.2.0
header_pages:
  - index.md
  - research-projects.md
  - publications-patents.md
  - education.md

