title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Control
remote_theme: Bilal2453/cayman-docs
header_pages:
  - index.md
  - research-projects.md
  - publications-patents.md
  - education.md

