title: Rahul Mallik
description: Power Electronics Engineer | Specialized in Converter Modeling & Control
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# This tells the theme which links to show in the sidebar/header
nav_links:
  - title: Home
    url: /
  - title: Research Projects
    url: /research-projects/
  - title: Publications
    url: /publications-patents/
  - title: Education
    url: /education/
